# This file was generated by GoReleaser. DO NOT EDIT.
class Nostromo < Formula
  desc "nostromo is a CLI to manage aliases through simple commands to add and remove scoped aliases and substitutions."
  homepage "https://nostromo.sh"
  version "0.7.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pokanop/nostromo/releases/download/v0.7.3/nostromo_0.7.3_Darwin_x86_64.tar.gz"
    sha256 "b34c0d1ff875098e46616cb0f172a191ab90a62feb231956a5b397840125f2a3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pokanop/nostromo/releases/download/v0.7.3/nostromo_0.7.3_Linux_x86_64.tar.gz"
      sha256 "ee615b5681125258f530da07e79066c9a2594021945aa6343d13c37b371c2a9e"
    end
  end

  def install
    bin.install "nostromo"
  end

  def caveats; <<~EOS
    Initialize nostromo and create a manifest under ~/.nostromo by running:
    
      nostromo init
    
    You can get started by running the following interactive command:
    
      nostromo add
  EOS
  end

  test do
    system "#{bin}/nostromo help"
  end
end
