# This file was generated by GoReleaser. DO NOT EDIT.
class Nostromo < Formula
  desc "nostromo is a CLI to manage aliases through simple commands to add and remove scoped aliases and substitutions."
  homepage "https://nostromo.sh"
  version "0.5.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pokanop/nostromo/releases/download/v0.5.0/nostromo_0.5.0_Darwin_x86_64.tar.gz"
    sha256 "4181eab20ff56a771e4ee33f6b0fea15db429dded0716eac7e1f304f13e38431"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pokanop/nostromo/releases/download/v0.5.0/nostromo_0.5.0_Linux_x86_64.tar.gz"
      sha256 "b3cbc370ae699c0e8162a56b517dfe392ffae157d4c3da6b3206e5e9f1ecc325"
    end
  end

  def install
    bin.install "nostromo"
  end

  def caveats; <<~EOS
    Initialize nostromo and create a manifest under ~/.nostromo by running:
    
      nostromo init
    
    You can add shell bindings for autocompletion adding these to your init file(s):
    
      eval "$(nostromo completion)" # for bash
      eval "$(nostromo completion --zsh)" # for zsh
  EOS
  end

  test do
    system "#{bin}/nostromo help"
  end
end
